addSbtPlugin("org.scalameta"      % "sbt-scalafmt"         % "2.4.6")
addSbtPlugin("com.github.sbt"     % "sbt-native-packager"  % "1.9.16")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"              % "0.4.4")
addSbtPlugin("com.github.sbt"     % "sbt-dynver"           % "5.0.1")
addSbtPlugin("io.shiftleft"       % "sbt-ci-release-early" % "2.0.19")
