addSbtPlugin("org.scalameta"      % "sbt-scalafmt"         % "2.5.4")
addSbtPlugin("com.github.sbt"     % "sbt-native-packager"  % "1.11.1")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"              % "0.4.4")
addSbtPlugin("com.github.sbt"     % "sbt-dynver"           % "5.1.0")
addSbtPlugin("io.shiftleft"       % "sbt-ci-release-early" % "2.1.2")
